baseurl: "https://statsandotherstuff.netlify.app"
title: "Statistics and other stuff in life's adventure"
author: Yi LIU
canonifyurls: yes
languagecode: en
theme: hugo-tanka
enableEmoji: yes
hasCJKLanguage: yes
pygmentsstyle: vs
pygmentscodefences: yes
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
params:
  faviconfile: images/favicon.ico
  highlightjs: yes
  highlightjslanguages:
    - r
    - python
    - stan
    - julia
  progressively: no
  sitename: Statistics and other stuff in life's adventure
  uselatex: yes
markup:
  goldmark:
    renderer:
      unsafe: yes
menu:
  primary:
    - name: Home
      url: https://statsandotherstuff.netlify.app/
      weight: 1
    - name: About
      url: /about/
      weight: 2
    - name: GitHub
      url: https://github.com/YiLIU001
      weight: 3
