---
title: Decision theory for covid test
author: Yi LIU
date: '2022-03-28'
slug: DecisionCovid1
categories:
  - Work
tags:
  - Stats
output:
  blogdown::html_page:
    toc: true
    toc_depth: 2
bibliography: [../Refs.bib]
biblio-style: "apalike"
link-citation: true
---

# Introduction

这两年来的covid疫情，影响了几乎所有人的生活。目前上海的疫情看起来十分严重，希望能够很快平息下去，我们又能过上正常的生活。

进来我们国家也开始有了对于covid的抗体（antigen, AG）检测，那么和之前的核酸（nucleic acid, NA）检测比较，那种收益更大，或者损失更小呢？本文就从一个及其粗浅的近似开始，利用决策理论（Decision Theory）来进行一些初步的分析。

# 分析框架，概念定义及假设

为了分析这个问题，我们需要先引入一些概念和假设。

## 二分类问题的评估标准

Covid检测是一个二分类问题。通常对于二分类检测方法的评估会用到四格表

| | True | False |
|---|---|---|
|Pos | TP | FP |
| Neg | FN | TN |

其中第一列的两个值表示检测结果，Pos（positive）或者Neg（negative）。第一行的两个值表示真实情况，True（患者）或者False（健康）。评估指标有很多种，比如机器学习里两个常用的是precision和recall。医学上，通常会用敏感度（sensitivity）和特异度（specificity）来评估。两者定义如下：

$$sen = P(test=Pos | disease=True) = \frac{TP}{TP + FN} = recall$$
$$spec = P(test=Neg | disease=False) = \frac{TN}{TN + FP}$$
从定义可以看出，敏感度是患者被检测出阳性的概率，而特异度是健康人群被检测出阴性的概率。对于抗体检测和核酸检测，一般来说核酸检测的敏感度和特异度都会比较高，即

$$sen_{NA} > sen_{AG}$$
$$spec_{NA} > spec_{AG}$$
其中，下标$NA$表示核酸检测，下标$AG$表示抗原检测。那么既然两个指标下都是核酸检测优于抗原检测，为什么还要提出抗原检测，直接用核酸检测就好了呀？这个有两方面的原因，一个是核酸检测成本较高（本文暂不考虑这个因素），另一个是核酸检测的capacity跟不上。后面我们会从决策理论出发，进行一些探讨。

## 损失函数

有了检测方法的二分类评估指标之后，我们需要再来定义在不同情况下的损失函数来量化评估两种检测方法的优劣。为此，我们引入不同情况下的损失函数，

$$loss(test, disease) = \left\{ \begin{aligned}
0, \text{ test=Pos and disease=True} \\ 
l_1, \text{ test=Pos and disease=False}\\
l_2, \text{ test=Neg and disease=True}\\
0, \text{ test=Neg and disease=False}\\
\end{aligned} \right.$$

这里我们假设了检测正确不会有损失，实际情况当然不会是这样。患者被检测出阳性会有后续治疗成本，但是目前我们先做一个粗糙的近似。根据常识，我们假设$l_1 \ll l_2$。

此外，我们还需要不检测情况下的损失函数。一个初步的近似是阳性的损失和阳性被误诊为阴性的损失一样，而阴性没有损失。

$$loss(no-test, disease) = \left\{ \begin{aligned} l_2, \text{ disease=True} \\ 0, \text{ disease=False} \end{aligned} \right.$$

## 关于人群及检测的其它假设

因为我们是考虑两种检测方法对于总体人群的收益，我们还需要做一些额外的假设。

第一个假设是关于人群里的患者比例$P_{cov}$，这个数值和接种疫苗比例有关，接种比例越高，患者比例越低。

第二个假设是两种检测方法的capacity或者说检测人数占总人口比例：$cap_{NA} = N^{tested}_{NA}/N^{tot} $和$cap_{AG} = N^{tested}_{AG}/N^{tot}$。我们假设$cap_{NA} < cap_{AG}$。

第三个假设是是否生病和检测与否，检测方法以及检测结果都无关，$P(disease=True|test)_{AG,NA} = P(disease=True|test=Positive)_{AG, NA} = P(disease) = P_{cov}$

# 损失计算

有了上面的假设和定义，我们可以计算使用两种不同检测方式的损失。下面我们先不考虑具体是哪种检测方式，计算出通用的损失表达式，然后再代入两种检测方式。

$$
\begin{aligned}
 & E(loss)\\
=& E(loss| \text{no-test})P(\text{no-test}) + E(loss| \text{test})_{AG}P(\text{test}) \\
=& E(loss| \text{no-test}) (1-cap) + E(loss| \text{test}) cap
\end{aligned}
$$

上式中的第一项内的期望可以计算得
$$
\begin{aligned}
 & E(loss|\text{no-test}) \\
=& loss(no-test, disease=True) P(disease=True|\text{no-test}) + loss(test, disease=False) P (disease=False | \text{no-test}) \\
=& l_2 P(disease=True|\text{no-test}) \\
=& l_2 P_{cov}
\end{aligned}
$$
第二项同样计算可得
$$
\begin{aligned}
 & E(loss|\text{test}) \\
=& loss(test, disease=True) P(disease=True|\text{test})\\
 &+ loss(test, disease=False) P (disease=False | \text{test}) \\
=& loss(test=Pos, disease=True) P(test=Pos| disease=True, \text{test}) P(disease=True| \text{test}) \\
 & +loss(test=Neg, disease=True) P(test=Neg| disease=True, \text{test}) P(disease=True| \text{test}) \\ 
 & + loss(test=Pos, disease=False) P(test=Pos| disease=False, \text{test}) P(disease=False| \text{test}) \\
 & + loss(test=Neg, disease=False) P(test=Neg| disease=False, \text{test}) P(disease=False| \text{test}) \\
=& \underbrace{loss(test=Pos, disease=True)}_{0} P(test=Pos| disease=True) P(disease=True) \\
 & +loss(test=Neg, disease=True) P(test=Neg| disease=True) P(disease=True) \\ 
 & + loss(test=Pos, disease=False) P(test=Pos| disease=False) P(disease=False) \\
 & + \underbrace{loss(test=Neg, disease=False)}_{0} P(test=Neg| disease=False) P(disease=False) \\
=& l_2 (1 - P(test=Pos| disease=True)) P(disease=True) \\
 & + l_1 (1 - P(test=Neg| disease=False)) P(disease=False) \\
=& l_2(1 - sen) P_{cov} + l_1 (1-spec) (1-P_{cov})
\end{aligned}
$$
因此，我们有
$$
\begin{aligned}
& E(loss)\\
=& l_2 P_{cov} (1 - cap) + l_2(1 - sen)P_{cov} cap + l_1 (1 - spec) (1 - P_{cov}) cap\\
=& 
\end{aligned}
$$
